spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: "${MAIL_FROM}"
    password: "${MAIL_APP_PASSWORD}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true